// import { Inter } from "next/font/google";
// import Head from "next/head";
// import { useEffect } from "react";

// const inter = Inter({ subsets: ["latin"] });

// export default function Home() {
//   useEffect(() => {
//     function getLocation() {
//       if (navigator.geolocation) {
//         navigator.geolocation.getCurrentPosition(showPosition);
//       } else {
//         console.log("Geolocation not supported");
//       }
//     }

//     async function showPosition(position) {
//       console.log("Position: ", position);

//       const response = await fetch(
//         `https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${position.coords.latitude}&longitude=${position.coords.longitude}&localityLanguage=en`
//       );
//       const result = await response.json();
//       console.log("Result: ", result);
//     }

//     getLocation();
//   }, []);

//   return (
//     <>
//       <Head>
//         <title>LiLu - Your Virtual Midwife</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <h1>LiLu</h1>
//     </>
//   );
// }

// import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

function Home() {
  const [latitude, setLatitude] = useState(null);
  const [longitude, setLongitude] = useState(null);
  const [principalSubdivision, setPrincipalSubdivision] = useState(null);

  useEffect(() => {
    function getLocation() {
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
      } else {
        console.log("Geolocation not supported");
      }
    }

    async function showPosition(position) {
      const { latitude, longitude } = position.coords;
      setLatitude(latitude);
      setLongitude(longitude);
      setPrincipalSubdivision(principalSubdivision);

      const response = await fetch(
        `https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${latitude}&longitude=${longitude}&localityLanguage=en`
      );
      const result = await response.json();
      console.log("Result: ", result);
    }

    getLocation();
  }, []);

  return (
    <>
      <Head>
        <title>LiLu - Your Virtual Midwife</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>LiLu</h1>

      {latitude && longitude && (
        <div>
          <p>Latitude: {latitude}</p>
          <p>Longitude: {longitude}</p>
          <p>{principalSubdivision}</p>
        </div>
      )}
    </>
  );
}
export default Home;
